# Generated by Django 4.1.3 on 2022-11-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='avatar',
            field=models.ImageField(upload_to='cover_images/<function user_directory_path at 0x7f293f3d3760>'),
        ),
    ]
