# Generated by Django 4.1.3 on 2022-11-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_blogauthor_slug_blogpost_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='cover_images/<function user_directory_path at 0x7f93b6bd7760>'),
        ),
    ]
